version: '3.9'

volumes:
    prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - prometheus-network
    restart: always
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - prometheus-network 
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--cluster.advertise-address=182.18.0.4:9093'
    networks:
      - prometheus-network 
    restart: always
    deploy:
      mode: global

  cadvisor:
    build: .
    privileged: true
    command:
      - '--allow_dynamic_housekeeping=true'
      - '--housekeeping_interval=30s'
      - '--docker_only=true'
      - '--storage_duration=1m0s'
      - '--event_storage_age_limit=default=0'
      - '--event_storage_event_limit=default=0'
      - '--global_housekeeping_interval=30s'
      - '--disable_metrics=accelerator,cpu_topology,disk,memory_numa,tcp,udp,percpu,sched,process,hugetlb,referenced_memory,resctrl,cpuset,advtcp,memory_numa'
      - '--store_container_labels=false'
    restart: unless-stopped
    devices:
      - /dev/kmsg:/dev/kmsg
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
    networks:
        - prometheus-network

  python_inst_app:
    build: python_app/.
    ports:
      - 8000:8000
      - 8001:8001
    restart: always
    deploy:
      mode: global
    networks:
        - prometheus-network

networks:
  prometheus-network:
    driver: bridge
    ipam:
        driver: default
        config:
          - subnet: 182.18.0.1/24
            gateway: 182.18.0.1
    name: prometheus-network

