version: '3.9'

volumes:
    prometheus_data: {}
    grafana_data: {}


services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - prometheus-network
    restart: always
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - prometheus-network 
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--cluster.advertise-address=182.18.0.4:9093'
    networks:
      - prometheus-network 
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - config.monitoring
    networks:
      - prometheus-network

networks:
  prometheus-network:
    driver: bridge
    ipam:
        driver: default
        config:
          - subnet: 182.18.0.1/24
            gateway: 182.18.0.1
    name: prometheus-network

